# Site Web Configuration for MindHub
site_name: MindHub
site_author: User15060
site_url: https://User15060.github.io/MindHub/
site_description: MindHub offers free cheatsheets across multiple domains
repo_url: https://github.com/User15060/MindHub
repo_name: MindHub
edit_uri: edit/main/docs/



# Template and Theme Configuration
theme:
  name: material
  logo: assets/MindHub_Logo.png
  favicon: assets/MindHub_Logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections        
    # - navigation.expand          
    - toc.follow                
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate 
    - content.tabs.link
    - content.action.edit

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.snippets


nav:
  - Home: Home/home.md
  - CheatsSheet:
      - Introduction: CheatsSheet/main.md
      - Language:
          - HTML:
              - 01-Structure: CheatsSheet/Language/HTML/01-HTML Structure/index.md
              - 02-Balises: CheatsSheet/Language/HTML/02-Balises/index.md
              - 03-Exemple:
                  - Exemple 1: CheatsSheet/Language/HTML/03-Exemple/index1.md
                  - Exemple 2: CheatsSheet/Language/HTML/03-Exemple/index2.md
          - CSS: CheatsSheet/Language/CSS/ # (mettre un index.md ou page par défaut)
  - Contact: Contact/contact.md
  - About Us: About Us/about.md


plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
      strict: false
  - minify:
      minify_html: true

extra_css:
  - StylesSheet/styleMain.css

# ... (le reste de ta config)





plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
      strict: false
  - minify:
      minify_html: true

extra_css:
  - StylesSheet/styleMain.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/User15060/MindHub

